### ISSUE TITLE
 confused about some code

### ISSUE THREAD

**Issue by bohr** [Zefan-Cai/PyramidKV#6]
https://github.com/Zefan-Cai/PyramidKV/blob/main/pyramidkv/pyramidkv_utils.py#L113C1-L121C1  

       max_capacity_prompt = max_num - self.layer_idx * steps
        
        # print(f"debug max_capacity_prompt {max_capacity_prompt}")
        
        
        if q_len < self.max_capacity_prompt - self.window_size:
            return key_states, value_states
        elif q_len < (self.max_capacity_prompt - self.window_size) * 2:

Why is self.max_capacity_prompt used under these two conditions, instead of the max_capacity_prompt calculated for each layer?
So in this code ，if the cache is reduced by less than 50%, it would be completely the same as snapkv.

**Comment by Zefan-Cai** [comment]
Thank you for pointing out!

These two conditions are made to avoid size mismatch. As you can see, if q_len < self.max_capacity_prompt - self.window_size, there is no need to do kv cache compression as the context size is larger than the input size. If q_len < (self.max_capacity_prompt - self.window_size) * 2, there will be a size mismatch issue in shallow layers as the context size of the first layer Is close to (self.max_capacity_prompt - self.window_size) * 2. The situation of q_len < (self.max_capacity_prompt - self.window_size) * 2 will lead to the size mismatch issue of input size < context size.
In order to avoid this issue, we set the second condition.

As you can see, this work targets at memory-constrained setting, so we only consider the settings where the context size is much smaller than the input size (i.e., more than 4k input size with 64, 128, 256, etc kv cache size), so our current implementation do not consider the cases where the cache size is more than 50% of the input size.

In the current setting, the length of the top layer and the bottom layer are fixed, thus the size mismatch issue is inevitable when q_len < (self.max_capacity_prompt - self.window_size) * 2.
We would introduce new settings where users can determine the size of top layer and bottom Layer to avoid this size mismatch issue and support the aforementioned cases.

Thank you so much for your support!

**Comment by Zefan-Cai** [comment]
Our current evaluations in LongBench and Needle do not consider the aforementioned settings of cases where the cache size is more than 50% of the input size. We will introduce new code to resolve your mentioned issue in the coming week.

**Comment by bohr** [comment]
Thank you very much for your explanation!
